### PR TITLE
SU Fix

### PR DESCRIPTION
**Pull request by thetronjohnson**

### CODE REVIEW

**Comment by thetronjohnson** [comment]
@abhinavprasad47 Eda postman itt test chyumbo I'm getting a bad request... onn nokkamo
-  Copy Paste Resource : https://www.beyondscale.tech/multiple-custom-user-auth-models-in-django-rest-framework

**Comment by thetronjohnson** [comment]
@sarathshaji714 Dithanu dath

**Comment by sarathshaji714** [comment]
Nannayi

**Comment by thetronjohnson** [comment]
Stack.pop("python/django")
Stack.push("node/express")

**Pull request closed without merging**
